### ISSUE TITLE
Added items are all weeds

### ISSUE THREAD

**Issue by cdthomas9** [colecrouter/stardew-save-editor#23]
I have a 1.6.7 install running modded with SVE and after I edited my file any items I added were weeds. The quantities were correct but the items themselves were not. I also added a couple of iridium tools and they all had a red circle slash icon and said error for the name. It looked like each tool had the correct graphic when using it, the pickaxe was a pickaxe and the axe was an axe, but the coloring looked like it was the standard item not upgraded at all.

**Comment by ArjhanToteck** [comment]
It looks like the item id is set to 0 for added items

**Comment by ArjhanToteck** [comment]
I tried looking through the code to make a fix and create a pull request, but I would need to edit the content files, which are in the gitignore, so I can't.

**Comment by colecrouter** [comment]
> I'm having the same issue, it looks like the item id is set to 0 for added items. However, I manually edited the item ids and that fixed the issue. [This site](https://mateusaquino.github.io/stardewids/) has a list of ids.

If the item IDs are the issue, then that's an easy fix. I had assumed that the numeric IDs weren't being used in the updated item formats, but it's entirely possible that this isn't 100% the case (or that SVE relies on them). Thanks for the info.

I've pushed an update to add the item IDs to all new items, hopefully that resolves it mostly. There are still a handful of items (such as tools) that are still not working since the 1.6 update. This is because item names no longer map 1:1 to tools (e.g. Iridium Axe -> Axe), and that's what iteminfo.json uses, and the rest of the app expects. (I just checked, creating an Iridium Axe makes just a normal Axe)

> Should these files be added to the repository?

I am trying to avoid uploading assets copied "directly" from the game, to avoid a possible DMCA as much as possible (the bar is already low 😬). There are some instructions in the CONTRIBUTING.md; those instructions tell you how to get files for the content folder (from your own install of the game), then `dump.ts` is in charge of spitting them out in a slightly less plagiarized format.

**Comment by ArjhanToteck** [comment]
> I am trying to avoid uploading assets copied "directly" from the game
That makes sense lol and yeah i shouldve read the contributing file

**Comment by nonocutt** [comment]
After the update, the item name shows correctly. However, I still can't use the items and their values are $0 (I tried the iridium sprinkler)

**Comment by colecrouter** [comment]
I think it should be fixed now. There were a group of items w/ specific behaviors that weren't getting the right IDs. Just tested with a sprinkler, worked fine.

Someone mentioned something similar in another issue, so if that works now, I'll go ahead and close both.

**Comment by Temporalin** [comment]
I had this problem (I needed 3 Iridium Sprinklers) two days ago, but I've tried again just now and it works, thanks
